### ISSUE TITLE
Markbot Required properties

### ISSUE THREAD

**Issue by jdawsonadams** [jdawsonadams/making-responsive-grids#1]
@hellachella

All my screenshots match up and I have no errors except for the fact that Markbot "expected to see width with a different value inside .l-1-3 in the 60 media query". I'm almost positive the width for that media query would have to be 33.33% if the screen is being shared by 3 grids so I'm not sure what else Markbot would be expecting.

**Comment by hellachella** [comment]
Were you able to complete this? So sorry I didn't get this, my notifications were turned off for github. I just got them up and running.
